function F_N = SupportDetection(F,L0,L0_dot,L0_ddot,Tp,ddtheta,ddz_M,dtheta,theta)
%SupportDetection
%    F_N = SupportDetection(F,L0,L0_dot,L0_ddot,Tp,DDTHETA,ddz_M,DTHETA,THETA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-07-31 20:46:13

t2 = cos(theta);
t3 = sin(theta);
F_N = ddz_M.*(3.0./2.0e+1)+F.*t2-L0_ddot.*t2.*(3.0./2.0e+1)+L0.*ddtheta.*t3.*(3.0./2.0e+1)+L0_dot.*dtheta.*t3.*(3.0./1.0e+1)+(Tp.*t3)./L0+L0.*dtheta.^2.*t2.*(3.0./2.0e+1)+1.47e+2./1.0e+2;
end
